[TACO-1476] Add purge account endpoint
Zone5-Cloud/z5-sdk-swift pull request #53
Opened 2022-07-11 19:07 UTC by tww0003

### What?

Adds the purge account endpoint to the SDK
### Why?

To allow us to conform to the App Store guidelines 

### How?

Implemented the end point

### Testing Plan

- I tested this by pulling this branch into the ride app, created a burner account, then sending the request to delete the burner account. After the request responded as successful, I would attempt to sign into the burner account again and see that I was denied. 

### Metadata
- Ticket(s): [TACO-1476](https://jira.specialized.com/browse/TACO-1476)
- Relevant Design(s):

2022-07-11 19:30 UTC, charliebartel requested changes

2022-07-11 19:30 UTC, charliebartel commented on Zone5/Views/UsersView.swift
> +		let endpoint = Endpoints.purgeAccount
Unit test coverage is needed for this change.  See UsersViewTests for examples.

2022-07-12 00:33 UTC, jeanhall requested changes
I think you will find that this doesn't work. The purge endpoint is not on the Zone5 server. It is a Lambda Clark wrote and it has a different base url.

Take a look at the ExternalView.swift class, and an example usage in the ExampleApp's ContentView.swift.

You will want something like this:

`enum ExternalEndpoints: String, InternalRequestEndpoint, RequestEndpoint {
	case purge = "https://api.staging.specialized.com/purge/api/v1/request"
}`
...	
`Zone5.shared.external.request(ExternalEndpoints.purge, method: .post, completion: voidreturningcompletion)`

The purge endpoint can be defined in the App codebase, so no changes are actually required to the sdk. But if you want this added to the sdk you can probably figure out a way to add it to the ExternalView, but remember the purge endpoint's baseURL needs to be configurable as it can be staging or prod.

2022-07-12 21:55 UTC, tww0003 commented
> I think you will find that this doesn't work. The purge endpoint is not on the Zone5 server. 

I did run into this issue and asked Clark R. about it. He advised we use `api.specialied.com`/`api.staging.specialized.com` as the base url for Today’s Plan moving forward and since we pass the base URL into the sdk from the app, I was able to get it to see it work. 

Here’s our thread for reference: https://jira.specialized.com/browse/OP-732

> It is a Lambda Clark wrote and it has a different base url.

I was unaware that this was just a lambda function and not added in the backend code, but pending confirmation that we should be using the specialized domain going forward in the above thread, do you advise we move this endpoint into ExternalView or the app itself?

2022-07-12 22:05 UTC, jeanhall commented
> > I think you will find that this doesn't work. The purge endpoint is not on the Zone5 server.
> 
> I did run into this issue and asked Clark R. about it. He advised we use `api.specialied.com`/`api.staging.specialized.com` as the base url for Today’s Plan moving forward and since we pass the base URL into the sdk from the app, I was able to get it to see it work.
> 
> Here’s our thread for reference: https://jira.specialized.com/browse/OP-732
> 
> > It is a Lambda Clark wrote and it has a different base url.
> 
> I was unaware that this was just a lambda function and not added in the backend code, but pending confirmation that we should be using the specialized domain going forward in the above thread, do you still advise we move this endpoint into ExternalView or the app itself? Since this is an App Store requirement and both the lead out and ride app need to consume it, it would seem like the users view would be the appropriate place for this endpoint.

Thanks for linking the thread. I was unaware devops had ported the wildfly server to the new domain. In that case I think your approach of adding it to the SDK is fine.

2022-07-12 22:07 UTC, jeanhall approved these changes

2022-07-12 22:12 UTC, jakeheis approved these changes

2022-07-12 22:21 UTC, charliebartel approved these changes

2022-07-12 22:22 UTC, merged